[splunkversioncontrol_backup://gitbackup]
debugMode = 1
disable_file_deletion = 0
disable_git_ssl_verify = 1
file_per_ko = 0
gitRepoURL = git@github.com:d33bu/test.git
gitTempDir = /home/deebu/test
git_branch = main
git_command = git
git_email = deebu.rajan@gmail.com
git_name = d33bu
noDisabled = 0
noPrivate = 0
remoteAppName = SplunkVersionControl
run_ko_diff = 0
run_ko_query = 0
show_passwords = 0
srcPassword = 
srcURL = https://localhost:8089
srcUsername = 
ssh_command = ssh
sslVerify = false
useLocalAuth = 1
use_wdiff = 0
interval = */10 * * * *
disabled = 1
