[id]
name = splunk_app_for_splunk_o11y_cloud
version = 1.2.1

[ui]
is_visible = 1
label = Discover Splunk Observability Cloud
show_in_nav = true
supported_themes = light,dark

[launcher]
author = Splunk
description = Demo and configuration of integration with the Splunk Observability suite.
version = 1.2.1

[package]
id = splunk_app_for_splunk_o11y_cloud
check_for_updates = 0

[install]
allows_disable = 1
build = 83d042ea
is_configured = 0

[triggers]
reload.splunk_create = simple
reload.splunk_app_for_splunk_o11y_cloud = simple
