#   Version 8.2.5
#
# This is the initial authorize.conf file for
# --> Discover Splunk Observability Cloud <--
# Use this file to configure roles and capabilities.
#
# To learn more about configuration files (including precedence) please see
# the documentation located at
# http://docs.splunk.com/Documentation/Splunk/latest/Admin/Aboutconfigurationfiles

#########################
##### CAPABILITIES #####
#########################
[capability::read_o11y_content]
disabled = 0

[capability::write_o11y_content]
disabled = 0

#########################
######## ROLES #########
#########################

[role_admin]
read_o11y_content = enabled
write_o11y_content = enabled

[role_power]
read_o11y_content = enabled
write_o11y_content = enabled

[role_user]
read_o11y_content = disabled
write_o11y_content = disabled
