[script:contact-sales]
match                 = /contact-sales
script                = contact_sales.py
scripttype            = persist
handler               = contact_sales.ContactSales
python.version        = python3
output_modes          = json
passPayload           = true

[script:o11y-tokens]
match                 = /o11y-tokens
script                = o11y_token_service.py
scripttype            = persist
handler               = o11y_token_service.TokenService
python.version        = python3
output_modes          = json
passPayload           = true

[script:o11y-metric-timeseries]
match                 = /o11y-metrictimeseries
script                = o11y_metric_timeseries.py
scripttype            = persist
handler               = o11y_metric_timeseries.O11yMetricTimeSeries
python.version        = python3
output_modes          = json
passPayload           = true
passSystemAuth        = true

[script:o11y-config]
match                 = /o11y-config
script                = o11y_config.py
scripttype            = persist
handler               = o11y_config.O11yConfigHandler
python.version        = python3
output_modes          = json
passPayload           = true
passSystemAuth        = true

[script:http-proxy]
match                 = /o11y/*
script                = o11y_http_proxy.py
scripttype            = persist
handler               = o11y_http_proxy.O11yHttpProxy
python.version        = python3
output_modes          = json
passPayload           = true
passSystemAuth        = true
