[expose:contact-sales]
pattern = /contact-sales
methods = POST

[expose:o11y-tokens]
pattern = /o11y-tokens
methods = GET, POST, DELETE

[expose:o11y-metric-timeseries]
pattern = /o11y-metrictimeseries
methods = GET, POST

[expose:o11y-config]
pattern = /o11y-config
methods = GET

[expose:http-proxy]
pattern = /o11y/**
methods = GET, POST
