[Bucket Copy Trigger]
description = Triggers bucket copying
cron_schedule = 17 * * * *
enableSched = 1
search = | archivebuckets

[Inactive Hadoop Data Roll Providers]
alert.severity = 5
alert.track = 1
counttype = number of events
cron_schedule = 17 0 * * *
description = Monitors for inactive Hadoop Data Roll (or otherwise virtual index) providers
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = | rest /services/data/vix-providers \
         | search NOT vix.hadoop_data_roll IN (1 t true y yes) \
         | fields title vix.family splunk_server archive_indexes virtual_indexes
