[audit_v-too_small]
PREFIX_SOURCETYPE = True
SHOULD_LINEMERGE = False
is_valid = True
maxDist = 9999

[cloudgateway_untracked-too_small]
PREFIX_SOURCETYPE = True
SHOULD_LINEMERGE = False
is_valid = True
maxDist = 9999

[first_install-too_small]
PREFIX_SOURCETYPE = True
SHOULD_LINEMERGE = False
is_valid = True
maxDist = 9999

[export_metrics-too_small]
PREFIX_SOURCETYPE = True
SHOULD_LINEMERGE = False
is_valid = True
maxDist = 9999

[splunk_o11y_app-too_small]
PREFIX_SOURCETYPE = True
SHOULD_LINEMERGE = False
is_valid = True
maxDist = 9999

[splunk_instrumentation-too_small]
PREFIX_SOURCETYPE = True
SHOULD_LINEMERGE = False
is_valid = True
maxDist = 9999

[splunk_archiver-too_small]
PREFIX_SOURCETYPE = True
SHOULD_LINEMERGE = False
is_valid = True
maxDist = 9999

[splunkversioncontrol_backup.log]
MAX_TIMESTAMP_LOOKAHEAD = 44
is_valid = True

[splunk_archiver-2]
MAX_TIMESTAMP_LOOKAHEAD = 49
SHOULD_LINEMERGE = False
is_valid = True

[splunkversioncontrol_backup.log-2]
is_valid = True

[splunkversioncontrol_backup.log-3]
MAX_TIMESTAMP_LOOKAHEAD = 44
is_valid = True

[splunkversioncontrol_backup.log-4]
MAX_TIMESTAMP_LOOKAHEAD = 44
is_valid = True

[splunkversioncontrol_backup.log-5]
MAX_TIMESTAMP_LOOKAHEAD = 44
is_valid = True

[git_for_splunk_gitforsplunk-too_small]
PREFIX_SOURCETYPE = True
SHOULD_LINEMERGE = False
is_valid = True
maxDist = 9999
