[wday_test]
client_id = MTc2NTIzMGQtNTgwNC00YzI0LWJmMzUtYjg2ZWJhMTg3NDdi
client_secret = ******
refresh_token = ******
token_endpoint = activityLogging
workday_rest_api_endpoint = https://wd5-services1.myworkday.com/ccx/api/privacy/vi1/zoom/
