######################################################
#
# Splunk RapidDiag
#
# Copyright (C) 2025 Splunk Inc. All Rights Reserved.
#
######################################################

[ui]
is_visible = 1
show_in_nav = 0
label = Splunk RapidDiag
docs_section_override = SplunkRapidDiag:1.9.5

[triggers]
reload.rapid_diag = simple

[launcher]
author = Splunk, Inc.
description = Splunk RapidDiag
version = 1.9.5

[install]
build = 31140884
is_configured = 0
