#   Version 20250117
#
# This file contains the tours available for Splunk Onboarding
#
# To update tours, copy the configuration block into
# ui-tour.conf in $SPLUNK_HOME/etc/system/local/. Restart the Splunk software to
# see the changes.
#
# To learn more about configuration files (including precedence) see the
# documentation located at
# http://docs.splunk.com/Documentation/Splunk/latest/Admin/Aboutconfigurationfiles
#

# Image Tour
[activities_per_user_audit-tour]
type = image
context = audit_trail
imageName1 = filters_tour_section.png
imageCaption1 = The Filters section allows you to select the data you want to analyze. Your selections impact the data displayed below in the presentation section and also affect the values available in dropdowns. Remember to use the 'Submit' button after selecting the appropriate values.
imageName2 = tabs_tour_section.png
imageCaption2 = Below filters section there is a data presentation part. It starts with tabs section, which allows to switch between different presentation sections.
imageName3 = overview_tour_section.png
imageCaption3 = The Overview tab provides an analytical presentation of data related to audited actions performed by human users across the Splunk ecosystem. It is useful for a general review of trends and anomaly detection.
imageName4 = activities_table_tour_section.png
imageCaption4 = The Activity Log tab provides more detailed data useful for investigations of specific anomalies and incidents. The source of the data is  _audit index.
imgPath = /tours/activities_per_user_audit
doneText = Go to Dashboard
doneURL = app/audit_trail/activities_per_user_audit


[knowledge_objects_audit-tour]
tourPage = knowledge_objects_audit
intro=Objects Modifications Dashboard Tour
type = image
imageName1 = filters_tour_section.png
imageCaption1 = The Filters section allows you to select the data you want to analyze. Your selections impact the data displayed below in the presentation section and also affect the values available in dropdowns. Remember to use the 'Submit' button after selecting the appropriate values.
imageName2 = tabs_tour_section.png
imageCaption2 = Below filters section there is a data presentation part. It starts with tabs section, which allows to switch between different presentation sections.
imageName3 = overview_tour_section.png
imageCaption3 = The Overview tab provides an analytical presentation of data related to audited changes in the state of Splunk’s knowledge objects, such as create, delete, and update actions. It is useful for a general review of trends and anomaly detection.
imageName4 = activity_table_tour_section.png
imageCaption4 = The Activity Log tab provides more detailed data useful for investigations of specific anomalies and incidents. The source of the data is  _audit index.
imgPath = /tours/knowledge_objects_audit
context = audit_trail
doneText = Go to Dashboard
doneURL = app/audit_trail/knowledge_objects_audit



# Interactive Tour
#[test-interactive-tour]
#type = interactive
#tourPage = reports
#urlData = data=foo&moredata=bar
#label = Interactive Tour Test
#stepText1 = Welcome to this test tour
#stepText2 = This is the first step in the tour
#stepElement2 = .test-selector
#stepText3 = This is the second step in the tour
#stepElement3 = .test-selector
#stepClickEvent3 = mousedown
#stepClickElement3 = .test-click-element
#forceTour = 1