#########################
##### CAPABILITIES #####
#########################
[capability::edit_data_management_pipeline]
[capability::edit_data_management_pipeline_job]
[capability::preview_data_management_pipeline]

#########################
######## ROLES #########
#########################
[role_admin]
edit_data_management_pipeline      = enabled
edit_data_management_pipeline_job  = enabled
preview_data_management_pipeline   = enabled

[role_data_management_admin]
# ==== Subsumed roles ====
importRoles = user
# ==== DM Capabilities   ====
edit_data_management_edgeprocessor = enabled
provision_data_management_agent    = enabled
edit_data_management_pipeline      = enabled
list_spl2_modules                  = enabled
edit_spl2_modules                  = enabled
edit_spl2_datasets                 = enabled
edit_data_management_pipeline_job  = enabled
run_spl2_search                    = enabled
preview_data_management_pipeline   = enabled
edit_tokens_all                    = enabled
# ==== Other Capabilities   ====
list_settings                      = enabled
edit_sourcetypes                   = enabled

# ==== Other settings ====
srchIndexesAllowed = *;_audit;_internal;_metrics;

[role_data_management_agent]
# ==== Subsumed roles ====
# ==== Capabilities   ====
edit_data_management_agent         = enabled
# ==== Other settings ====

[role_data_management_agent_spl2]
list_spl2_modules                  = enabled
edit_spl2_modules                  = enabled
edit_spl2_datasets                 = enabled
run_spl2_search                    = enabled
search                             = enabled
