[splunkversioncontrol_restore://gitrestore]
debugMode = 1
destURL = https://localhost:8089
disable_git_ssl_verify = 1
file_per_ko = 0
gitRepoURL = git@github.com:d33bu/test.git
gitTempDir = /home/deebu/test_restore
git_branch = main
index = git
remoteAppName = SplunkVersionControl
show_passwords = 0
sslVerify = false
useLocalAuth = 1

[splunkversioncontrol_backup://git_backup2]
appsList = example_csv,search,splunk-dashboard-studio
debugMode = 1
disable_file_deletion = 1
disable_git_ssl_verify = 1
file_per_ko = 1
gitRepoURL = git@github.com:d33bu/test_backup.git
gitTempDir = /home/deebu/test_backup
git_branch = main
git_command = git
git_email = deebu.rajan@gmail.com
git_name = d33bu
includeEntities = 
index = git
interval = * * * * *
noDisabled = 1
noPrivate = 0
remoteAppName = SplunkVersionControl
run_ko_diff = 1
run_ko_query = 1
show_passwords = 0
srcURL = https://localhost:8089
ssh_command = ssh
sslVerify = false
useLocalAuth = 1
use_wdiff = 1
disabled = 1
