[role_mcp_admin]
mcp_tool_admin = enabled
srchMaxTime = 8640000
srchTimeEarliest = -1
srchTimeWin = -1

[role_mcp_tool_execute]
mcp_tool_execute = enabled
srchMaxTime = 8640000
srchTimeEarliest = -1
srchTimeWin = -1

[role_mcp_tool_admin_execute]
mcp_tool_admin = enabled
mcp_tool_execute = enabled
srchMaxTime = 8640000
srchTimeEarliest = -1
srchTimeWin = -1
