[credential:postgres:postgres_admin:]
password = $7$R4UdzgLsFo0hVU4xQ3kRMmsJ1n56Qo6FRrMIQry7wkJ/ne4E2x9QdFdSsnzuZpPxwVx71fE77SeRyXBW+VUq/g==

[credential:postgres:do.root:]
password = $7$8G7cVIJMiciv4ZtWKTwFYnk7Lb5hygNV7bTYwT5vcr3FD+LXLZlScTGVSpUksoehCc7QGW/xXTRbozd2q7oMMw==

[credential:postgres:do.dbuser:]
password = $7$uR+nwcnXeEn0Ovyni2C9VQeW30ZU2JF4bw/RwKspGiFxek7hpMKbBlvCmOHFsuD4ZjrXFzrsUnIy4oLLiGL13g==

[credential:postgres:kvstore.pdl:]
password = $7$0EksWNG0fQV2CP5VfquwEAE3McTGoblsA2XFpzu8mPO3NrBOaTNujzfW4eLU7zCzceiS37axSTe8T+redyOuQQ==

[credential:postgres:acc.dbuser:]
password = $7$G4BJse4qeOo/M98JTMl3JOyHjfNXU6aqbftHmZso6HVmM3UgD7krz85jDtMzSrwkFtoFVO64fZ09dI1f4cFFvg==

[credential:postgres:oas.root:]
password = $7$UTSYDBZsfuZPplPV5KhYfNnuRt4gDf5hQflEODgYbAyo2/KHPDL030ZaA5RUpMamlBPYpXWtOvybqH5PllSACg==

[credential:postgres:oas.dbuser:]
password = $7$crqgNShybYAUs/gZvA7McfR8iobzVUEZDZo2n2l6IXuSOePc4oRP5AKmSeGjy7O277019XbO1Zqy1J/OkeRJqw==
