[default]

[general]
serverName = deebu-latitudee5470
pass4SymmKey = $7$LpSDXkt5ET8EYUG2wx7UlPJqXSsA1vJEXKJt6gmY7d4ZlOKF33u3Kg==
allowed_unarchive_commands = _auto,bzip2,gzip,zstd

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[sslConfig]
sslPassword = $7$LVJF46caP7YStb7Wibr4/X6mgry6H38THbTxXAweoIJ3Wzm/vD67WQ==

[version_control]
disabled = true

