[gitforsplunk://git_vc]
btool_conf_files = inputs, indexes, fields, props, limits, outputs, props, transforms, savedsearches, macros
include_btool_output = true
interval = 60
remote_push = true
repository_directory = .git/
working_directory = etc/
