[script:pipeline-manager]
match                 = /pipeline
script                = pipeline_endpoint.py
scripttype            = persist
capability            = (admin_all_objects) or (edit_data_management_pipeline)
handler               = application.PipelineManagerHandler
passPayload           = true
output_modes          = json


[script:list-pipelines]
match                 = /pipelines
script                = pipeline_endpoint.py
scripttype            = persist
capability            = (admin_all_objects) or (edit_data_management_pipeline)
handler               = application.PipelineManagerHandler
passPayload           = true
output_modes          = json

[script:edge-binary-server]
match                 = /dmx/packages/*/*/*/*
requireAuthentication = false
script                = edge_endpoint.py
scripttype            = persist
python.version        = python3
handler               = application.EdgeBinaryHandler

[eai:conf-pipeline]
capability.read=edit_data_management_pipeline or admin_all_objects
capability.write=edit_data_management_pipeline or admin_all_objects

[SBA:pipeline]
match=/properties/pipeline($|/)
capability.post=edit_data_management_pipeline or admin_all_objects
capability.put=edit_data_management_pipeline or admin_all_objects
capability.delete=edit_data_management_pipeline or admin_all_objects
capability.get=edit_data_management_pipeline or admin_all_objects 