[expose:pipeline-manager]
pattern = pipeline
methods = GET, POST, DELETE, PUT

[expose:list-pipelines]
pattern = pipelines
methods = GET

[expose:edge-binary-server]
pattern = dmx/packages/*/*/*/*
methods = GET